name: Docker Image CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Building image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
        
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up Google Cloud credentials
        run: echo "#### MY SECRET IS ${{ secrets.DOCKERHUB_USERNAME }}"
        
      # - name: Set up environment variable for Firebase
      #   run: echo "GOOGLE_APPLICATION_CREDENTIALS_JSON=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >> $GITHUB_ENV

      # - name: Build and push web image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: ./docker/web/Dockerfile
      #     push: true
      #     tags: markvovn/dentistry-be-web:latest

      - name: Build and push migration image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/migration/Dockerfile
          push: true
          tags: markvovn/dentistry-be-migration:latest
          build-args: |
            GOOGLE_APPLICATION_CREDENTIALS_JSON=${{ secrets.DOCKERHUB_USERNAME }}

  update_server:
      name: Updating prod environment
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Replacing container
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SERVER_HOSTNAME }}
            username: ${{ secrets.SERVER_USERNAME }}
            password: ${{ secrets.SERVER_PASSWORD }}
            script: |
              cd dentistry
              docker compose pull
              docker compose up -d
